[project]
name = "data-engineering-zoomcamp-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow-providers-google>=19.5.0",
    "dlt[workspace]>=1.22.2",
    "google-cloud-storage>=3.9.0",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "psycopg2-binary>=2.9.11",
    "pyarrow>=23.0.1",
    "scikit-learn>=1.8.0",
    "sqlalchemy>=2.0.48",
    "tqdm>=4.67.3",
]
